const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.filechooser,
		C3.Plugins.iframe,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.MoveAtAngle
	];
};
self.C3_JsPropNameTable = [
	{固体: 0},
	{物理: 0},
	{kago: 0},
	{kusa: 0},
	{sen: 0},
	{キーボード: 0},
	{file: 0},
	{sakuranbo: 0},
	{kaki: 0},
	{iframe: 0},
	{candrop: 0},
	{スプライト3: 0},
	{iframe2: 0},
	{itigo: 0},
	{budou: 0},
	{dekoponn: 0},
	{suteru: 0},
	{ringo: 0},
	{nasi: 0},
	{momo: 0},
	{painappuru: 0},
	{meron: 0},
	{スプライト: 0},
	{スプライト2: 0},
	{スプライト4: 0},
	{haikei: 0},
	{スプライト6: 0},
	{プログレスバー: 0},
	{ボタン: 0},
	{スプライト7: 0},
	{ゲームパッド: 0},
	{kuurudaun: 0}
];

self.InstanceType = {
	kago: class extends self.ISpriteInstance {},
	kusa: class extends self.ISpriteInstance {},
	sen: class extends self.ISpriteInstance {},
	キーボード: class extends self.IInstance {},
	file: class extends self.IFileChooserInstance {},
	sakuranbo: class extends self.ISpriteInstance {},
	kaki: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	スプライト3: class extends self.ISpriteInstance {},
	iframe2: class extends self.IIframeInstance {},
	itigo: class extends self.ISpriteInstance {},
	budou: class extends self.ISpriteInstance {},
	dekoponn: class extends self.ISpriteInstance {},
	suteru: class extends self.IButtonInstance {},
	ringo: class extends self.ISpriteInstance {},
	nasi: class extends self.ISpriteInstance {},
	momo: class extends self.ISpriteInstance {},
	painappuru: class extends self.ISpriteInstance {},
	meron: class extends self.ISpriteInstance {},
	スプライト: class extends self.ISpriteInstance {},
	スプライト2: class extends self.ISpriteInstance {},
	スプライト4: class extends self.ISpriteInstance {},
	haikei: class extends self.ISpriteInstance {},
	スプライト6: class extends self.ISpriteInstance {},
	プログレスバー: class extends self.IProgressBarInstance {},
	ボタン: class extends self.IButtonInstance {},
	スプライト7: class extends self.ISpriteInstance {},
	ゲームパッド: class extends self.IInstance {}
}